#_________________________________________________________________
# RestartMePlus has created by frpitu
# Twitter: @mechamopitu
# Github: https://gtihub.com/frpitu
# Youtube: @nitendinbr
#_________________________________________________________________
# Here, you enable or disable the countdown,
# with values, 'true' for enbale and 'false' for disable
#_________________________________________________________________
restart-enable: true
#_________________________________________________________________
# Here, you determine the server's Reset time, in minutes
# Example: 60 = 1h 120 = 2h (formula: 60.hours)
#________________________________________________________________
restart-time: 60
#_______________________________________________________________
# Here you define the type of message that will appear,
# being: message = 0, popup = 1, tip = 2
#_______________________________________________________________
restart-msgType: 0
#_______________________________________________________________
# Here is the message about how long it takes to reset the server
# Use {TIME} to show remaining time
#_______________________________________________________________
restart-broadcastTimeMsg: 'Server is shutdowning in {TIME}.'
#_______________________________________________________________
# Here it transmits the countdown, when it is close to resetting.
# Use {TIME} to show remaining time
#_______________________________________________________________
restart-serverIsStoppingMsg: 'Server is shutdowning in {TIME}!'
#_______________________________________________________________
# Here kick the player with the customized message
#_______________________________________________________________
restart-kickMsg: 'Srever reseting...'